### ISSUE TITLE
Create an easy to download link for getting the guide

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#114]
no one should have to download 500 MB of dependencies just to get the guide
a one-click, here-is-the-pdf download would be very welcome for someone just evaluating SAFETAG.

**Comment by elationfoundation** [comment]
Added overview to Safetag website as a download. http://safetag.org/overview.pdf Still need to add the other guides when they are polished for public consumption.

**Comment by elationfoundation** [comment]
In the 1.0 release only the SAFETAG framework content will be included in the repository and all compiled content will be linked in the readme and available under releases.

**Comment by joncamfield** [comment]
Pre-1.0 releases also have the compiled PDFs.
