### ISSUE TITLE
Add a section to the guide that introduces "how to read the guide"

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#115]
short and poignant, but only introduces the SAFETAG framework, not the guide – would be great to add what to expect and not expect from the guide

**Comment by elationfoundation** [comment]
Added ["How to read this guide"](https://github.com/OpenInternet/SAFETAG/blob/overview_overhaul/content/guides/how_to_read_this_guide.overview.md) to overview. Need to create one for each type of document.

**Comment by joncamfield** [comment]
There is also a guide version: https://github.com/OpenInternet/SAFETAG/blob/master/en/document_matter/how_to_read_this_guide.guide.md
