### ISSUE TITLE
Replace examples with activities in approaches section

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#144]
We are moving to a organizational structure of Objective->approach-(links to external)->activity. Where each objective (recon) has a set of approaches under it that are sorted by the needs of the organization. Each approach consists of links to a set of activities (which used to be examples) and are contained in an external folder.

e.g: 
The *Network assessment* objective can be done using a combination of the the *public_wireless* approach and the *SAAS_infrastructure* approach. The *public_wireless* approach uses the *wireshark_wireless_scanning* and *wireless_mapping* activities.

The folder structure for this example would look like this:

* objectives/
  * network_assessment/
    * approaches.md
    * approaches/
      * SAAS_infrastructure.md
      * public_wireless.md
* activities/
  * wireshark_wireless_scanning/
  * wireless_mapping/

Impacts #89 to help auditor make choices, or custom approaches based upon the needs of an organization.

**Comment by joncamfield** [comment]
See https://github.com/OpenInternet/SAFETAG/releases/tag/0.3 and https://github.com/OpenInternet/SAFETAG/wiki/Objectives-and-Activities-Map ; closing for now as "fixed"
