### ISSUE TITLE
Break apart and remove remote assessment.

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#149]
Split Reconnacance from "remote assessment" into its own section.
All active foot-printing will be places into network mapping.

**Comment by elationfoundation** [comment]
Moved the section. Still need to split out all the active footprinting.

**Comment by joncamfield** [comment]
Remote Assessment is no more, a reconnaissance method now exists with the relevant osint work, and other activities fall into network mapping.
