### ISSUE TITLE
We need to add a github-wiki page on different ways auditors can/do capture their notes throughout an audit

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#166]
There is currently no real support for auditors in identifying how to best keep their notes from an audit.  The github wiki is the proper place for this since it will encourage different auditors to more freely add to this content. This varies dramatically depending upon what an auditor is comfortable with and how they think so it should not be a part of the guide proper.

**Comment by joncamfield** [comment]
Stub page created at https://github.com/OpenInternet/SAFETAG/wiki/Auditor-Notes

**Comment by joncamfield** [comment]
Closing as an issue now that we have the wiki page created.
