### ISSUE TITLE
Make all guide sections compliant with new organizational structure

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#169]
The section organization has changed and the guides are not currently compliant. They need to match the new document structure as defined in the [document plan](https://github.com/OpenInternet/SAFETAG/blob/f9263a654c7c52fbce615264e10d23a4c642d02e/docs/documents.md)

**Comment by joncamfield** [comment]
Docs folder content is moved to the wiki, and the structure now matches the framework: https://github.com/OpenInternet/SAFETAG/wiki/Audit-Document-Structure
