### ISSUE TITLE
Should we remove the references folder and merge the references into their sections?

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#171]
Since we are moving all activity specific references into their activities there should be a lot less re-use of references between sections. With this, it might make sense to just create a references file for each section and get rid of the references folder to clean up the repository. What do you think?

**Comment by joncamfield** [comment]
There remains some cross-talk and re-use of references, and their separation also provides (as it always has) a nice centralized location for external guides/links/docs/etc.
