### ISSUE TITLE
Have the content builder identify what files are used when creating the document

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#172]
- have markdown-pp make a logfile of
  - what files it touches when it runs
  - what files were missing when it runs
  - what files were empty when it runs

This work will actually be done in the [markdown-pp repo](https://github.com/OpenInternet/markdown-pp) but we are keeping a central issue cue here.

**Comment by joncamfield** [comment]
Moved to https://github.com/OpenInternet/Documentation-Builder/issues/1
