### ISSUE TITLE
In the adids trainings we should to a user-device assessment of one of the trainee's

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#218]
This will show how it is done and the types of things that we are trying to accomplish with a user device assessment. It is not just looking at the computer for vulns or assessing if the user has bad practices, it is what used to be in interviews; a chance to get one on one interview time about the process' used in the organization, the reasoning behind user practices, the capabilities, barriers, etc. of that individual.

**Comment by joncamfield** [comment]
This exists as the Deepening for user device assessment
