### ISSUE TITLE
Change license to CC-BY-SA

### ISSUE THREAD

**Issue by joncamfield** [OpenInternet/SAFETAG#249]
We will Remove NC; further research reveals it may be too restrictive: http://freedomdefined.org/Licenses/NC ; http://mollykleinman.com/2008/08/21/cc-howto-2-how-to-use-a-work-with-a-noncommercial-license/

This also brings SAFETAG into license-parity with many other resources in the same space.

**Comment by snassar** [comment]
Hello @joncamfield do you have an update on this?

**Comment by elationfoundation** [comment]
Jon, you have full agreement on my to switch to CC-BY-SA. I am happy to switch it over & make a new release if you give the word. I am also cool with you making the changes and making a new release. Just let me know.

[Here is the license.](https://creativecommons.org/licenses/by-sa/3.0/)

We just need to change the license page I believe: 
- [English](https://github.com/OpenInternet/SAFETAG/blob/master/en/document_matter/license.md)
- [Spanish](https://github.com/OpenInternet/SAFETAG/blob/9e16568d2302f43aab3f4dbdfd9dafe1991664db/es/document_matter/license.md)

**Comment by seamustuohy** [comment]
The license has been updated to be CC-BY-SA.
