### ISSUE TITLE
Cryptocat was shutdown and should be removed

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#251]
Cryptocat is recommended in [in the operational security section.](https://github.com/OpenInternet/SAFETAG/blob/master/en/adids/operational_security/input.md)  This tool has been [shut down by its creator.](http://web.archive.org/web/20160222145547/https://crypto.cat/) It should be removed.

**Comment by elationfoundation** [comment]
Aaaaaaand, it is back online again.

**Comment by joncamfield** [comment]
It's back as a stand-alone app as opposed to a browser plugin.  We may still work to add new options (WhatsApp, Signal) for initial secure comms.
