### ISSUE TITLE
Split Interview questions by category to make custom interviews and training easier

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#29]
The  current organization is too cumbersom and gets in the way of training on why questions are asked, and how they can be leveraged.

**Comment by joncamfield** [comment]
See also #16

**Comment by elationfoundation** [comment]
Closed as no longer relevant since the interview section has been removed.

**Comment by elationfoundation** [comment]
It was actually just moved to be an activity... my bad.

**Comment by joncamfield** [comment]
The supporting appendix documents (https://github.com/OpenInternet/SAFETAG/blob/master/en/exercises/interviews/interview_questions.md) and capacity assessment cheat sheet (https://github.com/OpenInternet/SAFETAG/tree/master/en/exercises/capacity_assessment_cheatsheet) address this need
