### ISSUE TITLE
Create build tests in makefile to find dead links.

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#31]
We have encountered a few links that have died, even in the short initial componsition time-frame. We need to create a test that grabs every link and tests to see if they are up. Ideally, it would actually check against an md5 of each page to make sure that websites that don't throw a 404 are still seen as broken links.

This would also have to scrape off the #page=## from pdf's to not cause multiple links to the same pdf to be hit multiple times.

NOTE: ```egrep -hro "http.*\.pdf" * | sort | uniq```

**Comment by joncamfield** [comment]
Moved to https://github.com/OpenInternet/Documentation-Builder/issues/4
