### ISSUE TITLE
Dis-aggregate Context Research links

### ISSUE THREAD

**Issue by joncamfield** [OpenInternet/SAFETAG#45]
In context research, better segmentation or resources by subtopic
 * general news / events / politics - what are the top changes in the country recently? Would any of them impact the security situation
 * news about the organization itself (is the organization being attacked in the press or by bloggers? Have there been any big news stories about the organization?)
 * legal concerns (hacking, crypto, vpn usage)
 * technical threats (local trends in censorship, surveillance, malware, ddos...)

**Comment by elationfoundation** [comment]
I just read an interesting report that actually dis-aggregates a context assessment for conflict  using a series of pointed questions. I think the interview approach may both add needed disaggregation and make it clearer what can be found in each link.
