### ISSUE TITLE
Interviews: Add notes sheet

### ISSUE THREAD

**Issue by joncamfield** [OpenInternet/SAFETAG#46]
Add to examples and index, a "crib sheet" of outputs to take notes on during an interview to help with guiding the question flow

**Comment by elationfoundation** [comment]
Closed as completed, and also because we no longer have a interviews section.

**Comment by elationfoundation** [comment]
It was actually just moved to be an activity... my bad.

**Comment by joncamfield** [comment]
Now there's a crib sheet exercise for the capacity assessment method; at content/exercises/capacity_assessment_cheatsheet which meets this need.
