### ISSUE TITLE
"Highlight" key interview questions in Interview section

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#56]
The current HUGE list of questions in the interview section makes it difficult for auditors to identify key questions when in an interview. Key questions that cover important issues areas should be bolded or otherwise highlighted in the interview lists.

**Comment by elationfoundation** [comment]
Closed because interview section has been removed.

**Comment by elationfoundation** [comment]
It was actually just moved to be an activity... my bad.

**Comment by joncamfield** [comment]
The capacity assessment cheatsheet helps this dramatically
