### ISSUE TITLE
Add Google Search process as an activity

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#59]
The process of "googling" an organization strategically to identify staff, partners, locations, and sites needs to be added to the remote section as an example. We only have the automated and technical searches currently.

e.g.
```
link:site.org
related:site.org
site:site.org filetype:pdf (for metadata)
site:site.org filetype:doc  (for metadata)
filetype -> xml, xlsx, docx, etc...
```

**Comment by joncamfield** [comment]
423bb55 (to test) adds basic instructions for this exercise

**Comment by joncamfield** [comment]
Pushed to master
