### ISSUE TITLE
Add text about introductions to staff

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#60]
Walking around and introducing yourself and the process to the staff is critical to identify who "wants to be told what to do," and who "wants to be involved in the process." It also gives an auditor a chance to invite key individuals to take part in various activities that they would otherwise not attend. This relationship building is critical to a successful audit process, and we don't have any of it in the guide. So, we should add it.

**Comment by joncamfield** [comment]
now in master under the preparation section
