### ISSUE TITLE
current Wkhtmltopdf breaks metasploit and armatage on kali-linux

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#77]
When trying to install QT-compiled version of wkhtmltopdf used for html-pdf conversion of current SAFETAG documentation metasploit and armatage are broken. 

- Used debian wheezy 36bit download for wkhtmltopdf
- ERROR encountered: 
When using the graphical installer faced the following error.
```
GDBuc.Error:org.gtk.GDBus.UnmappedGError.Quark._pk_5ftransaction_5ferror.Code4:SimulateInstallFiles not supported by backend
```

An earlier version of wkhtmltopdf is a required package by other applications.

Using the following command allowed the latest version to be installed. But, it set metsploit, armatage and kali-linux-full to be de-installed because they don't recognize the QT version to be the same package as the one they require. As long as you don't use apt-get after this they won't get de-installed. But, we don't use them anyway with SAFETAG core so this currently works.

```
apt-get remove wkhtmltopdf
dpkg --install  [WKHTMLTOPDF.deb]
apt-get install -f
```

**Comment by elationfoundation** [comment]
This should stay open. We need to actually find an upstream fix to this. SAFETAG breaking metasplit is just silly.

**Comment by elationfoundation** [comment]
This issue should be moved to the SAFETAG document creator repository issue cue once it is separated from this repository.

**Comment by joncamfield** [comment]
moved to https://github.com/OpenInternet/Documentation-Builder/issues/5
