### ISSUE TITLE
Check for Different pandoc versions to provide table of contents if supported.

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#81]
Kali-Linux and Debian wheezy currently only offer pandoc version 1.9.4.2.  It seems that Ubuntu is running 1.12 with ```---toc-depth``` support. We should add pandoc version checking to produce different outputs in the future.

See: https://github.com/OpenInternet/SAFETAG/issues/79
RE: https://github.com/OpenInternet/SAFETAG/pull/76

**Comment by elationfoundation** [comment]
This issue should be moved to the SAFETAG document creator repository issue cue once it is separated from this repository.

**Comment by joncamfield** [comment]
Moved to https://github.com/OpenInternet/Documentation-Builder/issues/3
