### ISSUE TITLE
Ability to build individual sections with refs, appendices

### ISSUE THREAD

**Issue by joncamfield** [OpenInternet/SAFETAG#82]
It should be possible to build a specific SAFETAG guide section that pulls in the relevant endnotes and appendices (e.g. example/ content)  for that section.

**Comment by elationfoundation** [comment]
This is very possible. Currently the makefile just targets the main index's. We would want to actually script up the current builder to be more than a makefile. Once we do this it could do much much more. 

```
INDEX=path/to/index/file.md
INDEX_NAME=file_name
create_your_own: | $(SRC_DIR) $(DOC_DIR)
	modules/markdown-pp/markdown-pp.py $(INDEX) $(SRC_DIR)/$(INDEX_NAME).md
	pandoc -s --variable=title:"$(INDEX_NAME)" \
		--template=theme/html5.template \
		--to=html5 $(SRC_DIR)/$(INDEX_NAME).md \
		--output=$(SRC_DIR)/$(INDEX_NAME).html 
	wkhtmltopdf --user-style-sheet theme/core.css \
		--title "$(INDEX_NAME)" \
		--disable-smart-shrinking  \
		--load-error-handling skip \
		--load-media-error-handling skip \
		--footer-center "Page [page] of [toPage]" \
		--header-left [doctitle] \
		--outline \
		--outline-depth 2 \
		$(SRC_DIR)/$(INDEX_NAME).html $(DOC_DIR)/$(INDEX_NAME).pdf || true

```

**Comment by elationfoundation** [comment]
This issue should be moved to the SAFETAG document creator repository issue cue once it is separated from this repository.

**Comment by joncamfield** [comment]
Moved to Document Builder: https://github.com/OpenInternet/Documentation-Builder/issues/2
