### ISSUE TITLE
Enable make (guides) to compile PDFs offline

### ISSUE THREAD

**Issue by joncamfield** [OpenInternet/SAFETAG#84]
The css font usage of google causes wkhtmltopdf to fail to make PDFs.  This can be manually fixed by removing the references to gstatic in core.css and manually running the wkhtmltopdf command:

wkhtmltopdf --user-style-sheet theme/local.css --title "SAFETAG ADIDS Curricula"  --disable-smart-shrinking --footer-center "Page [page] of [toPage]" --header-left [doctitle] --outline --outline-depth 2 build/src/adids.html adids.pdf

An offline fallback would be nice though.  See https://github.com/OpenInternet/SAFETAG/commit/5869983ce6c7cbdf011059c205ce88cd59924d99 for the addition of a local.css file as a temporary workaround.

**Comment by elationfoundation** [comment]
This issue should be moved to the SAFETAG document creator repository issue cue once it is separated from this repository.

**Comment by joncamfield** [comment]
Works; already working in the document builder repo
