### ISSUE TITLE
Add self-taught excercises to pre-training curricula

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#97]
Throwing excercises at participants before the training to get them in the headspace and surface information about the participants' level of comfort with different aspects of the process. Exercises that would be self-starting might include LiveUSB creation, adding packages to their Kali that you find useful, overthewire exercises, making the guide, testing nmap on your home network, etc

**Comment by joncamfield** [comment]
Added a "homework" section to the pre-training curricula guide
