### ISSUE TITLE
Add guidance to send overview & guides to students far before training into curricula 

### ISSUE THREAD

**Issue by elationfoundation** [OpenInternet/SAFETAG#98]
Send the guide and agenda well in advance, but also assign chapters to read before the training as the guide is quite long and intimidating for the uninitiated.

For guidance [SaferJourno has a list of things to send to a participant of a TOT beforehand in its Managing Expectations section ](https://saferjourno.internews.org/pdf/SaferJourno_Guide.pdf#page=8).

**Comment by elationfoundation** [comment]
We could also include instructions on how to make the guide from git beforehand along-side the guide itself.

**Comment by joncamfield** [comment]
There is now an entire pre-training section which covers this.
